challenges_list_top: list[tuple[str, str, str, str, dict[str, str]]] = [
    ("Slaughterhouse Spam", "116995082", "Repeated 9 times spam from Slaughterhouse but without decoration. I accidentally beat it once lol xD", "None", {"Minh": "0zf8fClSpPw", "Djo2x": "uJCV6Vz4WQ8"}),
    ("RubRub", "114906934", "A random layout with a random name. It's also known as \"MysticNull Challenge\" or \"Litox Challenge\"", "lvV6n0OnDJ8", {"Uranium": "DTAxFikLK0w", "Djo2x": "LoU1AbU8uCg"}),
    ("Shitty 3sh In Hell", "128358030", "wiiiiiiiiiw (shitty 3sh x9)", "", {"Uranium": "2rgodvXJvF0", "Djo2x": "zAaY4po0sWY"}),
    ("Shitty Delusion", "128811828", "shitty d but longer", "", {"Uranium": "AcgS6zucacE", "Djo2x": "aoFD9MsM7XE"}),
    ("Shitty D", "128376571", "what a torture to build these structures loll", "", {"Minh": "YFrNHz8jwN8", "Djo2x": "aoFD9MsM7XE"}),
    ("Challenge", "123878042", "Open verification to bring Uranium back in the game :) (success)", "", {"Uranium": "laFShh49SGw", "Djo2x": "IrnjH15NGC4", "Xkcal": "jw5iy6R6HdQ"}),
    ("Spam VIII", "119573592", "Very long blue orbs ball spam.", "None", {"Uranium": "-ksCPqt1qyU", "Djo2x": "LoU1AbU8uCg"}),
    ("Swing Challenge", "123439096", "A level built for the challenge swap with Ylissen. We has 10 minutes to build and verify. A video about it is coming soon", "None", {"MysticNull": "gWtEkYCUri0", "Djo2x": "LoU1AbU8uCg"}),
    ("12qwe2d1", "108396972", "A remake of a wave challenge \"12qwe2d\" from the recent tab.", "hwpEIjr2yK4", {"Uranium": "wAk654ofMr8", "Minh": "YEOkGWvpyXI", "Djo2x": "Z_tqwxRz7JQ"}),
    ("Wave Challenge Final", "116005641", "The layout of a random wave challenge.", "12kSrHiKKy8", {"Uranium": "-ksCPqt1qyU", "Djo2x": "LoU1AbU8uCg"}),
    ("LegendOfConsistensy", "92834008", "2 players mode consistensy challenge.", "89DMw4Mizag", {"Uranium": "DzTbL22toR8", "Djo2x": "LoU1AbU8uCg"}),
    ("DaughterHouse", "91833325", "A wave consistensy challenge I made a longtime ago. The demon at the beginning is my sister.", "None", {"Uranium": "-ksCPqt1qyU", "Djo2x": "LoU1AbU8uCg"}),
    ("Shitty Endless River", "127610296", "X5 River's part from Shitty Slaughterhouse + ending verified by Roxy", "", {"Roxy": "78VvdYYHg6I", "Uranium": "MVpXlyuSz1o", "Minh": "3lRV889CUCA", "Djo2x": "Op_QTHJdT9wU"}),
    ("SpaM VII", "117690307", "Loooooong swing straight fly.", "None", {"Djo2x": "LoU1AbU8uCg"}),
    ("Pushing On", "106145402", "Small wave consistensy challenge, the structure is repeated 4 times", "Fk_E80P2xo0", {"Uranium": "DzTbL22toR8", "Djo2x": "LoU1AbU8uCg"}),
    ("RI Wave x2", "92957129", "Rainbow had an \"impossible\" version and this is the wave from that version but two times in a row.", "4qaz8HmjEiA", {"Uranium": "DzTbL22toR8", "Djo2x": "LoU1AbU8uCg"}),
    ("SpaM I", "98669660", "First level from the SpaM series, it gave me a headache lol. Black orbs spam with cube", "-3mQ4wV0zag", {"Uranium": "-ksCPqt1qyU", "Djo2x": "LoU1AbU8uCg"}),
    ("Cube Challenge", "123317744", "A level built for the challenge swap with Ylissen. We has 10 minutes to build and verify. A video about it is coming soon", "None", {"MysticNull": "gWtEkYCUri0", "Djo2x": "LoU1AbU8uCg"}),
    ("Ship Challenge", "123318508", "A level built for the challenge swap with Ylissen. We has 10 minutes to build and verify. A video about it is coming soon", "None", {"Ylissen": "", "MysticNull": "gWtEkYCUri0", "Djo2x": "LoU1AbU8uCg"}),
    ("Wave Challenge Y", "123321027", "A level built for the challenge swap with Ylissen. We has 10 minutes to build and verify. A video about it is coming soon", "None", {"Ylissen": "", "MysticNull": "gWtEkYCUri0", "Djo2x": "LoU1AbU8uCg"}),
    ("Shitty VSC", "128014988", "a funny one", "None", {"Roxy": "mtMNCvue8oo", "Djo2x": "n9tLr7MAUl4"}),
    ("Shitty 3sh", "128354755", "wiw", "None", {"YTCrunchy": "lX7328XBd10", "Djo2x": "k03QIhNlMHQ"}),
    ("Spider Challenge", "123439088", "A level built for the challenge swap with Ylissen. We has 10 minutes to build and verify. A video about it is coming soon", "None", {"Ylissen": "", "MysticNull": "gWtEkYCUri0", "Djo2x": "LoU1AbU8uCg"}),
    ("UFO Challenge", "123320075", "A level built for the challenge swap with Ylissen. We has 10 minutes to build and verify. A video about it is coming soon", "None", {"Ylissen": "", "MysticNull": "gWtEkYCUri0", "Djo2x": "LoU1AbU8uCg"}),
    ("Robot Challenge", "123439077", "A level built for the challenge swap with Ylissen. We has 10 minutes to build and verify. A video about it is coming soon", "None", {"Ylissen": "", "MysticNull": "gWtEkYCUri0", "Djo2x": "LoU1AbU8uCg"}),
    ("Ball Challenge", "123319310", "A level built for the challenge swap with Ylissen. We has 10 minutes to build and verify. A video about it is coming soon", "None", {"Ylissen": "", "MysticNull": "gWtEkYCUri0", "Djo2x": "LoU1AbU8uCg"}),
    ("SpaM VI", "117690302", "Loooooong wave spam.", "None", {"Uranium": "DzTbL22toR8", "Djo2x": "LoU1AbU8uCg"}),
    ("SpaM V", "98737726", "Spam on spider.", "yolTjBAHFOs", {"Uranium": "-ksCPqt1qyU", "Djo2x": "LoU1AbU8uCg"}),
    ("SpaM IV", "98737697", "Easy UFO spam but the last click is tricky.", "tESDqZi61A4", {"Uranium": "-ksCPqt1qyU", "Djo2x": "LoU1AbU8uCg"}),
    ("SpaM III", "98737614", "Short easy wave spam.", "CEmyGhWZXtU", {"Uranium": "-ksCPqt1qyU", "Djo2x": "LoU1AbU8uCg"}),
    ("Unnamed", "91831572", "Straightfly challenge from Element 111 RG but easier.", "wX3nusb0ZHw", {"Uranium": "-ksCPqt1qyU", "Djo2x": "LoU1AbU8uCg"}),
    ("Shitty Diamond Dance", "127610277", "Verified by ItzLuis. Part from Shitty Sakupen Circles for fun.", "JwY4Hirgorw", {"ItzLuis": "b21aDb7bAD4", "Uranium": "-ksCPqt1qyU", "Djo2x": "LoU1AbU8uCg", "Minh": "3lRV889CUCA", "Frytkaaaa": "8PwiJoje7gY"}),
    ("SpaM II", "98737338", "Easy pink orbs spam on cube.", "Dz4hY_DQBa4", {"Uranium": "-ksCPqt1qyU", "Djo2x": "LoU1AbU8uCg"})
]

#    ("", "", "", "", {}),
