challenges_list_top: list[tuple[str, str, str, str, dict[str, str]]] = [
    ("Slaughterhouse Spam", "116995082", "Repeated 9 times spam from Slaughterhouse but without decoration. I accidentally beat it once lol xD", "None", {}),
    ("12qwe2d1", "108396972", "A remake of a wave challenge \"12qwe2d\" from the recent tab.", "hwpEIjr2yK4", {"Uranium": "wAk654ofMr8"}),
    ("RubRub", "114906934", "A random layout with a random name. It's also known as \"MysticNull Challenge\" or \"Litox Challenge\"", "lvV6n0OnDJ8", {"Uranium": "DTAxFikLK0w"}),
    ("Spam VIII", "119573592", "Very long blue orbs ball spam.", "None", {"Uranium": "-ksCPqt1qyU"}),
    ("Swing Challenge", "123439096", "A level built for the challenge swap with Ylissen. We has 10 minutes to build and verify. A video about it is coming soon", "None", {}),
    ("Wave Challenge Final", "116005641", "The layout of a random wave challenge.", "12kSrHiKKy8", {"Uranium": "-ksCPqt1qyU"}),
    ("LegendOfConsistensy", "92834008", "2 players mode consistensy challenge.", "89DMw4Mizag", {"Uranium": "DzTbL22toR8"}),
    ("DaughterHouse", "91833325", "A wave consistensy challenge I made a longtime ago. The demon at the beginning is my sister.", "None", {"Uranium": "-ksCPqt1qyU"}),
    ("SpaM VII", "117690307", "Loooooong swing straight fly.", "None", {}),
    ("Pushing On", "106145402", "Small wave consistensy challenge, the structure is repeated 4 times", "Fk_E80P2xo0", {"Uranium": "DzTbL22toR8"}),
    ("RI Wave x2", "92957129", "Rainbow had an \"impossible\" version and this is the wave from that version but two times in a row.", "4qaz8HmjEiA", {"Uranium": "DzTbL22toR8"}),
    ("SpaM I", "98669660", "First level from the SpaM series, it gave me a headache lol. Black orbs spam with cube", "-3mQ4wV0zag", {"Uranium": "-ksCPqt1qyU"}),
    ("Cube Challenge", "123317744", "A level built for the challenge swap with Ylissen. We has 10 minutes to build and verify. A video about it is coming soon", "None", {}),
    ("Ship Challenge", "123318508", "A level built for the challenge swap with Ylissen. We has 10 minutes to build and verify. A video about it is coming soon", "None", {"Ylissen": ""}),
    ("Wave Challenge Y", "123321027", "A level built for the challenge swap with Ylissen. We has 10 minutes to build and verify. A video about it is coming soon", "None", {"Ylissen": ""}),
    ("Spider Challenge", "123439088", "A level built for the challenge swap with Ylissen. We has 10 minutes to build and verify. A video about it is coming soon", "None", {"Ylissen": ""}),
    ("UFO Challenge", "123320075", "A level built for the challenge swap with Ylissen. We has 10 minutes to build and verify. A video about it is coming soon", "None", {"Ylissen": ""}),
    ("Robot Challenge", "123439077", "A level built for the challenge swap with Ylissen. We has 10 minutes to build and verify. A video about it is coming soon", "None", {"Ylissen": ""}),
    ("Ball Challenge", "123319310", "A level built for the challenge swap with Ylissen. We has 10 minutes to build and verify. A video about it is coming soon", "None", {"Ylissen": ""}),
    ("SpaM VI", "117690302", "Loooooong wave spam.", "None", {"Uranium": "DzTbL22toR8"}),
    ("SpaM V", "98737726", "Spam on spider.", "yolTjBAHFOs", {"Uranium": "-ksCPqt1qyU"}),
    ("SpaM IV", "98737697", "Easy UFO spam but the last click is tricky.", "tESDqZi61A4", {"Uranium": "-ksCPqt1qyU"}),
    ("SpaM III", "98737614", "Short easy wave spam.", "CEmyGhWZXtU", {"Uranium": "-ksCPqt1qyU"}),
    ("Unnamed", "91831572", "Straightfly challenge from Element 111 RG but easier.", "wX3nusb0ZHw", {"Uranium": "-ksCPqt1qyU"}),
    ("SpaM II", "98737338", "Easy pink orbs spam on cube.", "Dz4hY_DQBa4", {"Uranium": "-ksCPqt1qyU"})
]
