players: list[tuple[str, list[str], list[str], list[str]]] = [
    ("Gild56", ["@gild56gmd", "UA", "Gild56", "The owner and the coder of this website and the creator of all these levels :) Hardest: Acu on Android 60hz jump from CraZy in 1.5 year and 115k attempts (yea krazy)"], [], []),
    ("Toffelz", ["@toffelz", "FR", "", "A french player, playtester of Shitty Boobawamba. Hardest: Bloodbath / Aftermath"], [], []),
    ("MysticNull", ["@mystic_nullgmd", "US", "MysticNull", "A friend, YouTuber, and demon slayer from Florida. He verified Shitty Andromeda on video without even knowing that no one had ever completed it on video before, lol. He has his own Discord server and a website with a list that inspired this one ;) Hardest: Acu"], [], []),
    ("kevino", ["@qelzzu", "DO", "00kev", "A friend, the verifier of Psychedelique and the first vicor of Shitty Amethyst. Hardest: Future Funk"], [], []),
    ("Uranium", ["@UraniumGMD", "AZ", "", "A friend and the top 1 player of the list after farming all the levels, GG! :D Hardest: Auto Play Arena, Second hardest: Artificial Dreams"], [], []),
    ("Itwabosballss", ["@Picklehi27GD", "Unknown", "", "A person probably. Hardest: Reanimate"], [], []),
    ("Panzer", ["@TheRealPanzer", "Unknown", "", "A person probably"], [], []),
    ("Minhmnvnnet", ["@minhmnvnnet", "VN", "", "Minhmnvnnet // Minh - A skilled player from Vietnam. Hardest: Niwa"], [], []),
    ("Loliquiem", ["@loliquiemgd", "KR", "", "Challenge was created for his request. Hardest: Totem"], [], []),
    ("Ylissen", ["@Ylissen", "MA", "", "A friend and the top 5 (former top 4 xD) Morocco player on Global List (la dash orbe noire) Hardest: Hypersonic"], [], []),
    ("Tryqz", ["@Try4qz", "PL", "", "A player and a creator from Poland. Hardest: Nine Circles"], [], []),
    ("Djo2x", ["@GDIlHHHlI", "CV", "", "A player from Cabo Verde. THE farmer of this list, especially challenges XD, Hardest: Niwa"], [], []),
    ("Miquella", ["@Miquella7779", "MD", "", "Skilled player from Moldova"], [], []),
    ("AxisGD", ["@FireCyan803", "Unknown", "", "A person probably"], [], []),
    ("Ultraviolet", ["@Ultraviolet977", "Unknown", "", "A person probably"], [], []),
    ("ReypSuperior", ["@reypsuperior", "Unknown", "", "A person probably"], [], []),
    ("Matsuba", ["@MatsubaRELLA", "Unknown", "", "A person probably"], [], []),
    ("Kyon717", ["@kyon717", "Unknown", "", "A person probably"], [], []),
    ("AuguXD", ["@wasuretalover", "CL", "", "A player from Chile. Hardest: Wasureta asa jump from Moment"], [], []),
    ("ItzLuis", ["@", "ES", "", "A player from Spain. (wPofpof)"], [], []),
    ("Toshi", ["@ToshiGD13", "AR", "", "A friend from Argentina and a super skilled effect creator :)"], [], []),
    ("Ihv2010", ["@GD_Ihv", "ES", "", "the GOAT himself ;)"], [], []),
    ("YTCrunchy", ["@iamCRUNCHYYY", "FR", "", "A french player who verified shitty 3sh"], [], [])
]

#    ("", ["", "", "", ""], [], []),
