players: list[tuple[str, list[str], list[str], list[str]]] = [
    ("Gild56", ["@gild56gmd", "UA", "Gild56", "The owner and the coder of this website and the creator of all these levels :) Hardest: Acu on Android 60hz jump from CraZy in 1.5 year and 115k attempts (yea krazy)", ""], [], []),
    ("Toffelz", ["@toffelz", "FR", "", "A french player, playtester of Shitty Boobawamba. Hardest: Bloodbath / Aftermath", ""], [], []),
    ("MysticNull", ["@mystic_nullgmd", "US", "MysticNull", "A friend, YouTuber, and demon slayer from Florida. He verified Shitty Andromeda on video without even knowing that no one had ever completed it on video before, lol. He has his own Discord server and a website with a list that inspired this one ;) Hardest: Allegiance", ""], [], []),
    ("Kevino", ["@qelzzu", "DO", "00kev", "A friend, the verifier of Psychedelique and the first vicor of Shitty Amethyst. Hardest: Future Funk", ""], [], []),
    ("Uranium", ["@UraniumGMD", "AZ", "", "Hardest: Auto Play Arena | Hacked everything", "HACK"], [], []),
    ("Itwabosballss", ["@Picklehi27GD", "Unknown", "", "A person probably. Hardest: Reanimate", ""], [], []),
    ("Panzer", ["@TheRealPanzer", "Unknown", "", "A person probably", ""], [], []),
    ("Minh", ["@minhmnvnnet", "VN", "", "Minhmnvnnet // Minh - A skilled player from Vietnam. Hardest: Clarity // Admin", ""], [], []),
    ("Xkcal", ["@loliquiemgd", "KR", "", "Challenge was created for his request. Hardest: Totem // Aka Loliquiem", ""], [], []),
    ("Ylissen", ["@Ylissen", "MA", "", "A friend and the top 5 (former top 4 xD) Morocco player on Global List (la dash orbe noire) Hardest: Hypersonic // Bloodbath 17-100 + 90x2 (soon)", ""], [], []),
    ("Roxy", ["@R0XY_0-1", "PL", "", "A great player and a creator from Poland. Hardest: Shitty TS II // Admin", "UWU"], [], []),
    ("Djo2x", ["@GDIlHHHlI", "CV", "", "A player from Cabo Verde. THE farmer of this list, especially challenges XD, Hardest: Napalm", ""], [], []),
    ("Miquella", ["@Miquella7779", "MD", "", "Skilled player from Moldova", ""], [], []),
    ("AxisGD", ["@FireCyan803", "Unknown", "", "A person probably", ""], [], []),
    ("Ultraviolet", ["@Ultraviolet977", "Unknown", "", "A person probably", ""], [], []),
    ("ReypSuperior", ["@reypsuperior", "Unknown", "", "A person probably", ""], [], []),
    ("Matsuba", ["@MatsubaRELLA", "Unknown", "", "A person probably", ""], [], []),
    ("Kyon717", ["@kyon717", "Unknown", "", "A person probably", ""], [], []),
    ("AuguXD", ["@wasuretalover", "CL", "", "A player from Chile. Hardest: Wasureta asa jump from Moment", ""], [], []),
    ("ItzLuis", ["@ItzAndreasGD", "ES", "", "A player from Spain. (wPofpof)", ""], [], []),
    ("Toshi", ["@ToshiGD13", "AR", "", "A friend from Argentina and a super skilled effect creator :)", ""], [], []),
    ("Ihv2010", ["@GD_Ihv", "ES", "", "the GOAT himself ;) // Admin", "GILD"], [], []),
    ("YTCrunchy", ["@iamCRUNCHYYY", "FR", "", "A french player who verified shitty 3sh", ""], [], []),
    ("Ben", ["@bznztzplzyszvrythzng", "PH", "", "He died at the outro of shitty nullscapes lmaoooo", ""], [], []),
    ("ScOrbunn7", ["@Scorbunn7GD", "AR", "", "Aka erazor_delata", ""], [], []),
    ("Frytkaaaa", ["@FrytkaaaaGD", "PL", "", "Frytkaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa  |  Hardest: Shitty Acheron", "YEN"], [], []),
    ("Illyes", ["", "FR", "", "Top 1 player of Bourgogne-Franche-Compté | Hardest: KOCMOC", ""], [], []),
    ("Blue Orbe", ["", "FR", "", "Skilled player and creator | Hardest: Conclusion", ""], [], []),
    ("Qibli", ["", "FR", "", "Hardest: Widestep", ""], [], []),
    ("Humanoid", ["", "US", "", "Hardest: Bloodbath", ""], [], []),
    ("KirbyLuve", ["", "FR", "", "Hardest: Shardscapes", ""], [], []),
    ("Oasis313", ["", "FR", "", "Hardest: Moving Forward", ""], [], []),
    ("Sao", ["", "FR", "", "Hardest: Freedom08", ""], [], []),
    ("Lexizz", ["", "FR", "", "Hardest: Auditory Breaker", ""], [], []),
    ("SKYZ", ["", "FR", "", "Hardest: SWI", ""], [], []),
    ("Kikouiz", ["", "FR", "", "Hardest: Acu on phone! / Friend I coached from easy demon to first extreme", ""], [], [])
]

#    ("", ["", "", "", "", ""], [], []),
